FROM chechuironman/python-oc:2.1

RUN pip install --upgrade pip 
 
RUN mkdir -p /project/server
WORKDIR /project



RUN pip install pipenv
RUN pip install --upgrade --user pipenv
ENV PATH=/home/worker/.local/bin:$PATH

ENV APPSODY_MOUNTS=/:/project/userapp
ENV APPSODY_DEPS=/project/deps
ENV APPSODY_PROJECT_DIR=/project

ENV APPSODY_WATCH_DIR=/project/userapp
ENV APPSODY_WATCH_REGEX="^.*.py$"

ENV APPSODY_PREP="cd /project/userapp;pipenv lock -r > requirements.txt;python -m pip install -r requirements.txt -t /project/deps"

ENV APPSODY_RUN="python -m flask run --host=0.0.0.0 --port=8080"
ENV APPSODY_RUN_ON_CHANGE=$APPSODY_RUN
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="FLASK_ENV=development python -m ptvsd --host 0.0.0.0 --port 5678 -m flask run --host=0.0.0.0 --port=8080 --no-reload"
ENV APPSODY_DEBUG_ON_CHANGE=$APPSODY_DEBUG
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="python -m unittest discover -s test -p *.py"
ENV APPSODY_TEST_ON_CHANGE=$APPSODY_TEST
ENV APPSODY_TEST_KILL=false

COPY  ./LICENSE /licenses/
COPY  ./project /project
COPY  ./config /config

RUN pipenv lock -r > requirements.txt
RUN python -m pip install -r requirements.txt -t /project/deps
RUN python -m pip install ptvsd -t /project/deps

# The next line gets round a problem with flasgger in that it has an unnecessary requirement on
# jsonschema of < 3.0.0, while other components here need > 3.0.0. This is fixed in flasgger
# PR 317, but a new release has not yet been pushed to pypi. The line below and the constraints
# file can be removed once a new release is made (and flassger added to the regular Pipfile).
# This constraints workaround will still cause an error on docker build, but this can be ignored.
RUN python -m pip install --upgrade -c constraints.txt flasgger==0.9.3 -t /project/deps

ENV PYTHONPATH=/project/deps:/project/userapp/:/project/userapp/
ENV FLASK_APP=/project/server/__init__.py

ENV PORT=8080
EXPOSE 8080
EXPOSE 5678
